# Import libraries

In [1]:
import pandas as pd
import numpy as np
import os

# Load data

In [2]:
# define the path and assign dataframes to the "df" variables

path = r'C:\Users\Jakov\2023 Instacart Basket Analysis'

df_ords = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'orders_checked.csv'), index_col = 0)
df_prods = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'products_checked.csv'), index_col = 0)
df_ords_prods_comb = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_combined.pkl'))

# 04.

In [3]:
# check dimensions of the dataframe

df_ords_prods_comb.shape

(32434489, 11)

# 05., 06.

In [4]:
df_prods

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3
...,...,...,...,...,...
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3
49689,49685,En Croute Roast Hazelnut Cranberry,42,1,3.1
49690,49686,Artisan Baguette,112,3,7.8
49691,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,4.7
49692,49688,Fresh Foaming Cleanser,73,11,13.5

In [6]:
#delete '_merge column'

df_ords_prods_comb.drop('_merge', axis = 1, inplace = True)

MemoryError: Unable to allocate 990. MiB for an array with shape (4, 32434489) and data type int64

In [7]:
df_ords_prods_comb

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,orders_day_of_a_week,order_hour_of_day,days_since_prior_order,first_order_ever,_merge
0,2,33120,1,1,202279,3,5,9,8.0,False,both
1,2,28985,2,1,202279,3,5,9,8.0,False,both
2,2,9327,3,0,202279,3,5,9,8.0,False,both
3,2,45918,4,1,202279,3,5,9,8.0,False,both
4,2,30035,5,0,202279,3,5,9,8.0,False,both
...,...,...,...,...,...,...,...,...,...,...,...
32434484,3421083,39678,6,1,25247,24,2,6,21.0,False,both
32434485,3421083,11352,7,0,25247,24,2,6,21.0,False,both
32434486,3421083,4600,8,0,25247,24,2,6,21.0,False,both
32434487,3421083,24852,9,1,25247,24,2,6,21.0,False,both
32434488,3421083,5020,10,1,25247,24,2,6,21.0,False,both

In [9]:
#merge df_ords_prods_comb dataframe with df_prods dataframe with 'product_id' column as a common column

df_ords_prods_merged = df_ords_prods_comb.merge(df_prods, on = 'product_id')

MemoryError: Unable to allocate 247. MiB for an array with shape (32434489,) and data type int64

In [23]:
df_ords_prods_merged

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,orders_day_of_a_week,order_hour_of_day,days_since_prior_order,first_order_ever,product_name,aisle_id,department_id,prices,_merge
0,2,33120,1,1,202279,3,5,9,8.0,False,Organic Egg Whites,86,16,11.3,both
1,26,33120,5,0,153404,2,0,16,7.0,False,Organic Egg Whites,86,16,11.3,both
2,120,33120,13,0,23750,11,6,8,10.0,False,Organic Egg Whites,86,16,11.3,both
3,327,33120,5,1,58707,21,6,9,8.0,False,Organic Egg Whites,86,16,11.3,both
4,390,33120,28,1,166654,48,0,12,9.0,False,Organic Egg Whites,86,16,11.3,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32404854,3265099,43492,3,0,111311,2,3,10,5.0,False,Gourmet Burger Seasoning,104,13,4.8,both
32404855,3361945,43492,19,0,142932,25,3,10,5.0,False,Gourmet Burger Seasoning,104,13,4.8,both
32404856,3267201,33097,2,0,183867,19,3,18,3.0,False,Piquillo & Jalapeno Bruschetta,81,15,9.4,both
32404857,3393151,38977,32,0,79056,1,4,13,NaN,True,Original Jerky,100,21,1.5,both
32404858,3400803,23624,7,0,152189,4,3,14,2.0,False,Flatbread Pizza All Natural,79,1,1.6,both

In [25]:
df_ords_prods_merged['_merge'].value_counts()

both          32404859
left_only            0
right_only           0
Name: _merge, dtype: int64

# 07.

In [24]:
# export newly merged dataframe into pkl file

df_ords_prods_merged.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_with_names_merged.pkl'))

In [1]:
df_ords_prods_merged.shape

NameError: name 'df_ords_prods_merged' is not defined